# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 政见
subtitle: CNPolitcs Radio
description: 拆掉知识的高墙，让普通人接触社科学术研究中的新知和思想精华 radio.cnpolitics.org
author: 政见 CNPolitics.org
email: webmaster@cnpolitcs.org
copyright: 政见 CNPolitics.org, all rights reserverd.
language: default
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://radio.cnpolitics.org
root: /
permalink: :category/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: /
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  政正有词: meme
  政记干货大排档: pub
  政好读书: read
  讲座 & 访谈: scholar
  政常说话: talk
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/cnpolitics/radio
  branch: gh-pages
  message: Deploy

# Feeds
feed:
  type: rss2
  path: feed.xml
  limit: false

# Podcast metadata
podcast:
  cnp:
    title: 政见合集
    subtitle: CNPolitcs Radio
    url: http://radio.cnpolitics.org
    feed: http://radio.cnpolitics.org/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/cnpolitics-cover1400-v1.0.png
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 这里是政见出品的几档播客节目的合集。我们致力于拆掉知识的高墙，让普通人接触社科学术研究中的新知和思想精华。网站：cnpolitics.org；微信公众号：cnpolitics2011。
    copyright: 政见 CNPolitics.org
  meme:
    title: 政见｜政正有词
    subtitle: The Meme | CNPolitcs Radio
    url: http://radio.cnpolitics.org/meme
    feed: http://radio.cnpolitics.org/meme/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/meme-cover1400-v1.0.jpg
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 打开这本声音词典，花几分钟时间，轻松了解新鲜词汇和概念。政见 CNPolitics 出品。
    copyright: 政见 CNPolitics.org
  pub:
    title: 政见｜政记干货大排档
    subtitle: The Pub | CNPolitcs Radio
    url: http://radio.cnpolitics.org/pub
    feed: http://radio.cnpolitics.org/pub/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/pub-cover1400-v1.0.jpg
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 知识就像爱与美食，不可或缺，不能辜负。我们把最新的时事和最有意思的知识结合，为你送上新鲜的干货。政见 CNPolitics 出品。
    copyright: 政见 CNPolitics.org
  read:
    title: 政见｜政好读书
    subtitle: The Read | CNPolitcs Radio
    url: http://radio.cnpolitics.org/read
    feed: http://radio.cnpolitics.org/read/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/read-cover1400-v1.0.jpg
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 政见 CNPolitics 出品的读书节目。在这里，我们将与你分享优秀且优美的社科作品，用声音传递美与智慧。
    copyright: 政见 CNPolitics.org
  scholar:
    title: 政见｜讲座 & 访谈
    subtitle: The Scholar | CNPolitcs Radio
    url: http://radio.cnpolitics.org/scholar
    feed: http://radio.cnpolitics.org/scholar/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/scholar-cover1400-v1.0.jpg
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 政见 CNPolitics 举办的沙龙、讲座、访谈精彩内容，原声呈现，如临现场。
    copyright: 政见 CNPolitics.org
  talk:
    title: 政见｜政常说话
    subtitle: The Talk | CNPolitcs Radio
    url: http://radio.cnpolitics.org/talk
    feed: http://radio.cnpolitics.org/talk/feed.xml
    cover: http://radio.cnpolitics.org/assets/cover/talk-cover1400-v1.0.jpg
    author: 政见 CNPolitics.org
    email: webmaster@cnpolitcs.org
    description: 政见 CNPolitics 出品的聊天节目。我们正常说话，轻松聊天，把那些不说人话的深奥理论用简单的语言解释给你听。
    copyright: 政见 CNPolitics.org
